### ISSUE TITLE
Color of the circle in the plotfrom `sv_dependence()` 

### ISSUE THREAD

**Issue by arodionoff** [mayer79/shapviz#2]
Can you allow the color of the circle in the plot from `sv_dependence()` to be set to something other than purple, or even remove the color outline for the points on the plot? Like chart from `SHAPforxgboost::shap.plot.dependence()`

**Comment by mayer79** [comment]
Currently, there are two arguments:

- `color` and
- `color_var`

to control the point color.  

So, e.g., using the example in the vignette, you could write
``` r
sv_dependence(shp, v = "carat", color = "darkorange", alpha = 0.5)
```
to get all orange points:

![image](https://user-images.githubusercontent.com/16206095/173834110-39305458-5868-4ede-ad9f-d0cba0d58051.png)

Is this what you mean?

**Comment by arodionoff** [comment]
What about a plot with the Strongest interacting Variable? When you need use palette for some levels.

**Comment by mayer79** [comment]
There are two possibilities:

### Use `options()`

"shapviz" uses the following defaults:

``` r
shapviz.viridis_args = list(begin = 0.25, end = 0.85, option = "inferno")
```

You can change these e.g. by using standard viridis and reverting the scale:

```r
options(shapviz.viridis_args = list(option = "D", direction = -1))
```

Check `?scale_color_viridis_c` for more options.

### Use ggplot

"shapviz" returns a ggplot object, so you can simply add your own scale, like this:

```
sv_dependence(shp, v = "carat", color_var = "auto") +
  scale_color_viridis_d()
```
Note that you need to know whether the color scale should be discrete or continuous.

**Comment by arodionoff** [comment]
Thank you. I will use palette `inferno` as as a more contrasting one, since the default one will fill everything with a dark purple color.

What is your next step in the road map?

**Comment by mayer79** [comment]
Maybe your color variable has a gross outlier? It is easier to clip the outlier in the display data set X than to deal with color scales. The current default does not produce all purple values in the examples I had tested, so maybe it is something depending on your data. Or a bug, but without reproducible example, I cannot do anything.

Next will eventually be plots for SHAP interactions.

**Comment by arodionoff** [comment]
Thank you, I will with some palettes and contrasts for the best view for `sv_dependence()`

**Comment by mayer79** [comment]
I think it is a data issue, let me know if there is something wrong in the code.
