### ISSUE TITLE
{lightgbm} v4.0.0 is coming

### ISSUE THREAD

**Issue by jameslamb** [mayer79/shapviz#22]
👋 hey @mayer79 !

As you know from discussions we've had over in https://github.com/microsoft/LightGBM, at `{lightgbm}` has been accumulating breaking changes in preparation for a v4.0.0 release (https://github.com/microsoft/LightGBM/issues/5153).

To make up for the fact that so many of these changes are being released directly without a deprecation cycle (https://github.com/microsoft/LightGBM/pull/5133#issuecomment-1154580355), I'm willing to come here and contribute fixes to make `{shapviz}` compatible with both older and newer versions of `{lightgbm}`.

Are you open to such contributions?

I'd also be happy to document here in this issue how you and anyone contributing to this project can test it against the development version of LightGBM, if you think that'd help. (e.g., as I ddid here for `{bonsai}`: https://github.com/tidymodels/bonsai/issues/34#issuecomment-1186578635).

Thanks so much for all your contributions to LightGBM and for maintaining this package that allows people to get more information out of their LightGBM models!

**Comment by mayer79** [comment]
Hey James.  Thanks so much. "shapviz" works for the current master as well as for the CRAN version, see my comment/snippet on SHAPforxgboost. I need to keep an eye on XGBoost though. They are planning to change the predict interface as well.

**Comment by jameslamb** [comment]
Excellent, glad to hear it! `@` me in the future if you need any help.
