### ISSUE TITLE
Beeswarm plot: Connecting visualisations to waterfall-style plots

### ISSUE THREAD

**Issue by madprogramer** [mayer79/shapviz#28]
Today, I was working with a colleague. I explained how the waterfall plot has the advantage of focussing on a single entry, where the beeswarm plot offers a summary of the model. He then asked, if it would somehow be possible to combine the two:

- A beeswarm plot
- But showing where a single entry lands in the clouds of datapoints

Below is a mock-up of what this could look like:

```R
sv_importance(shp, kind = "beeswarm", row_id = 1)
```

![image](https://user-images.githubusercontent.com/3719664/185736008-817efbbc-0dec-497f-b6bf-e417f7c39a87.png)

`sv_importance` could take an additional param `row_id` to highlight the corresponding data points for the nth row of SHAP values, similar to waterfall and force. I don't think there is much freedom in color-choice here (if we want to make something colorblind-friendly), so maybe arrows and labels could be used to point at the approx. location of values.

Sound meaningful?

**Comment by mayer79** [comment]
The idea is good (also for dependence plots). Unfortunately, the implementation is surprisingly complex. For instance, how to find the vertical position of the points? I'd suggest that you simply show a screenshot like the one above to explain the plots (this is actually how I usually do *g)

**Comment by madprogramer** [comment]
Remark: It should be possible to query the corresonding row from the shapviz$X (values) or shapviz$S (importance) tables.

In fact, it should be possible to have complex query rules to filter these when the order of the specific row we're interested in is unknown.
