### ISSUE TITLE
sv_importance returns unused argument error

### ISSUE THREAD

**Issue by Karol-Gawlowski** [mayer79/shapviz#29]
Calling sv_importance results in:

`Error in FUN(newX[, i], ...) : unused argument (simplify = FALSE)`

Looking through shapviz/tree/main/R)/sv_importance.R; the _.min_max_scale_ helper function indeed does not include the simplify argument,

repro steps as in the shapviz vignette
```
X_train_test <- data.matrix(iris[, -1])
dtrain_test <- xgboost::xgb.DMatrix(X_train_test, label = iris[, 1])
fit_test <- xgboost::xgb.train(data = dtrain_test, nrounds = 50)
x_test <- shapviz(fit_test, X_pred = X_train_test)
sv_importance(x_test)
sv_importance(x_test, kind = "beeswarm", show_numbers = TRUE)
```

Note, the following works as intended:
`sv_importance(x_test, kind = "no")
`

Cheers

**Comment by mayer79** [comment]
Hello. The `simplify` option refers to `apply(..., simplify = FALSE)`, which was introduced in R 4.1. I was not aware of this version dependency, so I'd love to replace the snipped by something that also runs on lower R versions.

**Comment by mayer79** [comment]
Fixed by https://github.com/mayer79/shapviz/pull/30
