### ISSUE TITLE
Probabiliy on x-axis for a class

### ISSUE THREAD

**Issue by OlexiyPukhov** [mayer79/shapviz#32]
I am doing a classification task using xgboost. When calculating values with shapviz, is it possible to somehow scale the SHAP value into the scale of the probability of one of the two classes in a binary classification problem?

**Comment by mayer79** [comment]
Hello. A similar, but difficult to understand, question: https://github.com/mayer79/shapviz/issues/24

My answer currently is:

- If you know how to transform the SHAP values to probability scale, you can apply it and then use shapviz.
- Unfortunately, I don't think such a transformation exist.
- My other package,  `kernelshap`, can crunch SHAP values from any predict function. If you are willing to switch from TreeSHAP to Kernel SHAP, this might be an option. At least to get a feeling...

**Comment by OlexiyPukhov** [comment]
Thanks!
